//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHome.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Readout
    {
        public int Id { get; set; }
        public System.DateTime At { get; set; }
        public decimal Value { get; set; }
        public bool ActionOn { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
